config/routes.rb
Rails.application.routes.draw do
  get 'contacts/new'
  get 'contacts/create'
  root to: "pokecas#index"
  resources :pokecas, only: [:index, :show]
  resources :rares, only: [:index, :show]
  resources :genres, only: [:index, :show]
  resources :boxes, only: [:index, :show]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :pokecas
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :set_genre, only: [:show, :edit, :update, :destroy]

  # GET /genres
  # GET /genres.json
  def index
    @genres = Genre.all
  end

  # GET /genres/1
  # GET /genres/1.json
  def show
  end

  # GET /genres/new
  def new
    redirect_to root_path
    @genre = Genre.new
  end

  # GET /genres/1/edit
  def edit
    redirect_to root_path
  end

  # POST /genres
  # POST /genres.json
  def create
    @genre = Genre.new(genre_params)

    respond_to do |format|
      if @genre.save
        format.html { redirect_to @genre, notice: 'Genre was successfully created.' }
        format.json { render :show, status: :created, location: @genre }
      else
        format.html { render :new }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genres/1
  # PATCH/PUT /genres/1.json
  def update
    respond_to do |format|
      if @genre.update(genre_params)
        format.html { redirect_to @genre, notice: 'Genre was successfully updated.' }
        format.json { render :show, status: :ok, location: @genre }
      else
        format.html { render :edit }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genres/1
  # DELETE /genres/1.json
  def destroy
    @genre.destroy
    respond_to do |format|
      format.html { redirect_to genres_url, notice: 'Genre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genre
      @genre = Genre.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def genre_params
      params.require(:genre).permit(:name)
    end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/_form.html.haml
= form_with(model: genre, local: true) do |form|
  - if genre.errors.any?
    #error_explanation
      %h2
        = pluralize(genre.errors.count, "error")
        prohibited this genre from being saved:
      %ul
        - genre.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :name
    = form.text_field :name
  .actions
    = form.submit

app/views/genres/edit.html.haml
%h1 Editing Genre
= render 'form', genre: @genre
= link_to 'Show', @genre
|
= link_to 'Back', genres_path

app/views/genres/index.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  %a.navbar-brand{:href => root_path} POKEYARU
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto
      %li.nav-item
        %a.nav-link{:href => root_path} カード一覧
      %li.nav-item
        %a.nav-link{:href => boxes_path} 拡張BOXから探す
      %li.nav-item.active
        %a.nav-link{:href => genres_path}
          ジャンルから探す
          %span.sr-only (current)
      %li.nav-item
        %a.nav-link{:href => rares_path} レアリティから探す
      %li.nav-item
        %a.nav-link{:href => new_admin_user_session_path} 管理画面
    %form.form-inline.my-2.my-lg-0
      %input.form-control.mr-sm-2{"aria-label" => "Search", :placeholder => "Search", :type => "search"}/
      %button.btn.btn-outline-success.my-2.my-sm-0{:type => "submit"} Search
.container
  %h2.text-center.mb-3.mt-3 ジャンル一覧
  %table.table.table-striped.text-nowrap
    %thead
      %tr
        %th Name
    %tbody
      - @genres.each do |genre|
        %tr
          %td= genre.name

app/views/genres/new.html.haml
%h1 New Genre
= render 'form', genre: @genre
= link_to 'Back', genres_path

app/views/genres/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @genre.name
|
= link_to 'Back', genres_path