config/routes.rb
Rails.application.routes.draw do
  get 'contacts/new'
  get 'contacts/create'
  root to: "pokecas#index"
  resources :pokecas, only: [:index, :show]
  resources :rares, only: [:index, :show]
  resources :genres, only: [:index, :show]
  resources :boxes, only: [:index, :show]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/box.rb
class Box < ApplicationRecord
  has_many :pokecas
end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController
  before_action :set_box, only: [:show, :edit, :update, :destroy]

  # GET /boxes
  # GET /boxes.json
  def index
    @boxes = Box.all
  end

  # GET /boxes/1
  # GET /boxes/1.json
  def show
  end

  # GET /boxes/new
  def new
    redirect_to root_path
    @box = Box.new
  end

  # GET /boxes/1/edit
  def edit
    redirect_to root_path
  end

  # POST /boxes
  # POST /boxes.json
  def create
    @box = Box.new(box_params)

    respond_to do |format|
      if @box.save
        format.html { redirect_to @box, notice: 'Box was successfully created.' }
        format.json { render :show, status: :created, location: @box }
      else
        format.html { render :new }
        format.json { render json: @box.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boxes/1
  # PATCH/PUT /boxes/1.json
  def update
    respond_to do |format|
      if @box.update(box_params)
        format.html { redirect_to @box, notice: 'Box was successfully updated.' }
        format.json { render :show, status: :ok, location: @box }
      else
        format.html { render :edit }
        format.json { render json: @box.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boxes/1
  # DELETE /boxes/1.json
  def destroy
    @box.destroy
    respond_to do |format|
      format.html { redirect_to boxes_url, notice: 'Box was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_box
      @box = Box.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def box_params
      params.require(:box).permit(:name, :place, :release)
    end
end

app/helpers/boxes_helper.rb
module BoxesHelper
end

app/views/boxes/_form.html.haml
= form_with(model: box, local: true) do |form|
  - if box.errors.any?
    #error_explanation
      %h2
        = pluralize(box.errors.count, "error")
        prohibited this box from being saved:
      %ul
        - box.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :name
    = form.text_field :name
  .field
    = form.label :place
    = form.text_field :place
  .field
    = form.label :release
    = form.date_select :release
  .actions
    = form.submit

app/views/boxes/edit.html.haml
%h1 Editing Box
= render 'form', box: @box
= link_to 'Show', @box
|
= link_to 'Back', boxes_path

app/views/boxes/index.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  %a.navbar-brand{:href => root_path} POKEYARU
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto
      %li.nav-item
        %a.nav-link{:href => root_path} カード一覧
      %li.nav-item.active
        %a.nav-link{:href => boxes_path}
          拡張BOXから探す
          %span.sr-only (current)
      %li.nav-item
        %a.nav-link{:href => genres_path} ジャンルから探す
      %li.nav-item
        %a.nav-link{:href => rares_path} レアリティから探す
      %li.nav-item
        %a.nav-link{:href => new_admin_user_session_path} 管理画面
    %form.form-inline.my-2.my-lg-0
      %input.form-control.mr-sm-2{"aria-label" => "Search", :placeholder => "Search", :type => "search"}/
      %button.btn.btn-outline-success.my-2.my-sm-0{:type => "submit"} Search

.container
  %h2.text-center.mb-3.mt-3 拡張BOX一覧
  %table.table.table-striped.text-nowrap
    %thead
      %tr
        %th Name
        %th Place
        %th Release
    %tbody
      - @boxes.each do |box|
        %tr
          %td= box.name
          %td= box.place
          %td= box.release

app/views/boxes/new.html.haml
%h1 New Box
= render 'form', box: @box
= link_to 'Back', boxes_path

app/views/boxes/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @box.name
%p
  %strong Place:
  = @box.place
%p
  %strong Release:
  = @box.release
|
= link_to 'Back', boxes_path