config/routes.rb
Rails.application.routes.draw do
  get 'contacts/new'
  get 'contacts/create'
  root to: "pokecas#index"
  resources :pokecas, only: [:index, :show]
  resources :rares, only: [:index, :show]
  resources :genres, only: [:index, :show]
  resources :boxes, only: [:index, :show]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/rare.rb
class Rare < ApplicationRecord
  has_many :pokecas
end

app/controllers/rares_controller.rb
class RaresController < ApplicationController
  before_action :set_rare, only: [:show, :edit, :update, :destroy]

  # GET /rares
  # GET /rares.json
  def index
    @rares = Rare.all
  end

  # GET /rares/1
  # GET /rares/1.json
  def show
  end

  # GET /rares/new
  def new
    redirect_to root_path
    @rare = Rare.new
  end

  # GET /rares/1/edit
  def edit
    redirect_to root_path
  end

  # POST /rares
  # POST /rares.json
  def create
    @rare = Rare.new(rare_params)

    respond_to do |format|
      if @rare.save
        format.html { redirect_to @rare, notice: 'Rare was successfully created.' }
        format.json { render :show, status: :created, location: @rare }
      else
        format.html { render :new }
        format.json { render json: @rare.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rares/1
  # PATCH/PUT /rares/1.json
  def update
    respond_to do |format|
      if @rare.update(rare_params)
        format.html { redirect_to @rare, notice: 'Rare was successfully updated.' }
        format.json { render :show, status: :ok, location: @rare }
      else
        format.html { render :edit }
        format.json { render json: @rare.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rares/1
  # DELETE /rares/1.json
  def destroy
    @rare.destroy
    respond_to do |format|
      format.html { redirect_to rares_url, notice: 'Rare was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rare
      @rare = Rare.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rare_params
      params.require(:rare).permit(:rarity)
    end
end

app/helpers/rares_helper.rb
module RaresHelper
end

app/views/rares/_form.html.haml
= form_with(model: rare, local: true) do |form|
  - if rare.errors.any?
    #error_explanation
      %h2
        = pluralize(rare.errors.count, "error")
        prohibited this rare from being saved:
      %ul
        - rare.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :rarity
    = form.text_field :rarity
  .actions
    = form.submit

app/views/rares/edit.html.haml
%h1 Editing Rare
= render 'form', rare: @rare
= link_to 'Show', @rare
|
= link_to 'Back', rares_path

app/views/rares/index.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  %a.navbar-brand{:href => root_path} POKEYARU
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto
      %li.nav-item
        %a.nav-link{:href => root_path} カード一覧
      %li.nav-item
        %a.nav-link{:href => boxes_path} 拡張BOXから探す
      %li.nav-item
        %a.nav-link{:href => genres_path} ジャンルから探す
      %li.nav-item.active
        %a.nav-link{:href => rares_path}
          レアリティから探す
          %span.sr-only (current)
      %li.nav-item
        %a.nav-link{:href => new_admin_user_session_path} 管理画面
    %form.form-inline.my-2.my-lg-0
      %input.form-control.mr-sm-2{"aria-label" => "Search", :placeholder => "Search", :type => "search"}/
      %button.btn.btn-outline-success.my-2.my-sm-0{:type => "submit"} Search
.container
  %h2.text-center.mb-3.mt-3 レアリティ一覧
  %table.table.table-striped.text-nowrap
    %thead
      %tr
        %th Rarity
    %tbody
      - @rares.each do |rare|
        %tr
          %td= rare.rarity

app/views/rares/new.html.haml
%h1 New Rare
= render 'form', rare: @rare
= link_to 'Back', rares_path

app/views/rares/show.html.haml
%p#notice= notice
%p
  %strong Rarity:
  = @rare.rarity
|
= link_to 'Back', rares_path