config/routes.rb
Rails.application.routes.draw do
  get 'contacts/new'
  get 'contacts/create'
  root to: "pokecas#index"
  resources :pokecas, only: [:index, :show]
  resources :rares, only: [:index, :show]
  resources :genres, only: [:index, :show]
  resources :boxes, only: [:index, :show]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pokeca.rb
class Pokeca < ApplicationRecord
  belongs_to :box
  belongs_to :genre
  belongs_to :rare
  mount_uploader :image, ImageUploader

  def thumbnail
    return self.image.variant(resize: '300x300').processed
  end
  
end

app/controllers/pokecas_controller.rb
class PokecasController < ApplicationController
  before_action :set_pokeca, only: [:show, :edit, :update, :destroy]

  # GET /pokecas
  # GET /pokecas.json
  def index
    @q = Pokeca.ransack(params[:q])
    @pokecas = @q.result.order(id: "DESC").page(params[:page]).per(12)
  end

  # GET /pokecas/1
  # GET /pokecas/1.json
  def show
  end

  # GET /pokecas/new
  def new
    redirect_to root_path
    @pokeca = Pokeca.new
  end

  # GET /pokecas/1/edit
  def edit
    redirect_to root_path
  end

  # POST /pokecas
  # POST /pokecas.json
  def create
    @pokeca = Pokeca.new(pokeca_params)

    respond_to do |format|
      if @pokeca.save
        format.html { redirect_to @pokeca, notice: 'Pokeca was successfully created.' }
        format.json { render :show, status: :created, location: @pokeca }
      else
        format.html { render :new }
        format.json { render json: @pokeca.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pokecas/1
  # PATCH/PUT /pokecas/1.json
  def update
    respond_to do |format|
      if @pokeca.update(pokeca_params)
        format.html { redirect_to @pokeca, notice: 'Pokeca was successfully updated.' }
        format.json { render :show, status: :ok, location: @pokeca }
      else
        format.html { render :edit }
        format.json { render json: @pokeca.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pokecas/1
  # DELETE /pokecas/1.json
  def destroy
    @pokeca.destroy
    respond_to do |format|
      format.html { redirect_to pokecas_url, notice: 'Pokeca was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pokeca
      @pokeca = Pokeca.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pokeca_params
      params.require(:pokeca).permit(:image, :name, :detail, :price, :box_id, :genre_id, :rare_id)
    end
end

app/helpers/pokecas_helper.rb
module PokecasHelper
end

app/views/pokecas/_form.html.haml
= form_with(model: pokeca, local: true) do |form|
  - if pokeca.errors.any?
    #error_explanation
      %h2
        = pluralize(pokeca.errors.count, "error")
        prohibited this pokeca from being saved:
      %ul
        - pokeca.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :image
    = form.text_field :image
  .field
    = form.label :name
    = form.text_field :name
  .field
    = form.label :detail
    = form.text_area :detail
  .field
    = form.label :price
    = form.text_field :price
  .field
    = form.label :box_id
    = form.text_field :box_id
  .field
    = form.label :genre_id
    = form.text_field :genre_id
  .field
    = form.label :rare_id
    = form.text_field :rare_id
  .actions
    = form.submit

app/views/pokecas/edit.html.haml
%h1 Editing Pokeca
= render 'form', pokeca: @pokeca
= link_to 'Show', @pokeca
|
= link_to 'Back', pokecas_path

app/views/pokecas/index.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  %a.navbar-brand{:href => root_path} POKEYARU
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto
      %li.nav-item.active
        %a.nav-link{:href => root_path}
          カード一覧
          %span.sr-only (current)
      %li.nav-item
        %a.nav-link{:href => boxes_path} 拡張BOXから探す
      %li.nav-item
        %a.nav-link{:href => genres_path} ジャンルから探す
      %li.nav-item
        %a.nav-link{:href => rares_path} レアリティから探す
      %li.nav-item
        %a.nav-link{:href => new_admin_user_session_path} 管理画面

    = search_form_for @q do |f|
      %form.form-inline.my-2.my-lg-0
        = f.search_field :name_cont, placeholder: "カード名で検索", class: "form-control mr-sm-2"
      = f.submit "検索", class: "btn btn-outline-success my-2 my-sm-0"

.jumbotron.jumbotron-fluid
  .container
    %h1.display-4.text-body ポケモンカードコレクション
    %p.lead.text-body 欲しい情報がすぐわかる！レアカード情報がいっぱい！
.container
  %h2.text-center.mb-3 コレクションカード一覧
  - @pokecas.each_slice(3) do |pokecas|
    %ul.list-group.list-group-horizontal-md
      - pokecas.each do |pokeca|
        %li.list-inline-item.card.mb-3.mx-auto{:style => "width: 20rem;"}
          .row
            .col-md-5.mw-100.mh-100
              .card-img
                = image_tag pokeca.image.thumb.url
            .col-md-7
              .card-body
                %h5.card-title.text-truncate= pokeca.name
                %p.card-text.text-black-50.text-truncate= pokeca.box.name
                %button.btn-outline-primary= link_to '詳細', pokeca
  .pagination= paginate @pokecas

app/views/pokecas/new.html.haml
%h1 New Pokeca
= render 'form', pokeca: @pokeca
= link_to 'Back', pokecas_path

app/views/pokecas/show.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  %a.navbar-brand{:href => root_path} POKEYARU
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto
      %li.nav-item
        %a.nav-link{:href => root_path} カード一覧
      %li.nav-item
        %a.nav-link{:href => boxes_path} 拡張BOXから探す
      %li.nav-item
        %a.nav-link{:href => genres_path} ジャンルから探す
      %li.nav-item
        %a.nav-link{:href => rares_path} レアリティから探す
    %form.form-inline.my-2.my-lg-0
      %input.form-control.mr-sm-2{"aria-label" => "Search", :placeholder => "Search", :type => "search"}/
      %button.btn.btn-outline-success.my-2.my-sm-0{:type => "submit"} Search

.container.text-center.mb-3
  = image_tag @pokeca.image.url
  %p
    %strong カード名:
    = @pokeca.name
  %p
    %strong カード詳細:
    = @pokeca.detail
  %p
    %strong 相場:
    = @pokeca.price
  %p
    %strong 収録ボックス:
    = @pokeca.box.name
  %p
    %strong ジャンル:
    = @pokeca.genre.name
  %p
    %strong レアリティ:
    = @pokeca.rare.rarity

  = link_to '戻る', pokecas_path

app/views/pokecas/test.html.erb
<%= serach_from_for @search do |f| %>
  <div class="field">
    <%= f.label :name_cont, "Name contains"%>
    <%= f.text.field :name_cont %>
  </div>
  <div class="actions"><%= f.submit "Search" %></div>